import Head from "next/head";
import Navbar from "@/components/Navbar";
import TopSection from "@/components/TopSection";
import About from "@/components/About";
import Services from "@/components/Services";
import Projects from "@/components/Projects";
import Testimonial from "@/components/Testimonial";
import Footer from "@/components/Footer";
import ContactMe from "@/components/ContactMe";
import { projectData, staticCardData, carouselCardData } from '../data/data';

export default function Home({ projectData, staticCardData, carouselCardData }) {
  return (
    <>
      <Head>
        <title>Portfolio website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <TopSection />
        <About />
        <Services data={staticCardData} />
        <Projects data={projectData} />
        <Testimonial data={carouselCardData} />
        <ContactMe />
        <Footer />
      </main>
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {
      projectData,
      staticCardData,
      carouselCardData
    }
  };
}
